esphome:
  name: christmas-countdown

esp8266:
  board: nodemcuv2

web_server:
  port: 80

wifi:
  ssid: "YOUR_SSID"
  password: "YOUR_PASSWORD"
  fast_connect: true

# Signal sensor to monitor connection quality in the Web UI
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s

output:
  - platform: esp8266_pwm
    pin: GPIO12
    id: buzzer_out
  - platform: gpio
    pin:
      number: GPIO2
      inverted: true # Active-low for most ESP8266 onboard LEDs
    id: onboard_led

# Global to track blink timing
globals:
  - id: last_blink
    type: uint32_t
    initial_value: '0'

# Connectivity Monitoring Logic
interval:
  - interval: 100ms # High-frequency check to handle fast blinking
    then:
      lambda: |-
        bool wifi_connected = wifi::global_wifi_component->is_connected();
        bool ntp_synced = id(sntp_time).now().is_valid();
        uint32_t now_ms = millis();

        if (!wifi_connected) {
          // FAST BLINK (No WiFi): Toggle every 200ms
          if (now_ms - id(last_blink) >= 200) {
            id(onboard_led).toggle();
            id(last_blink) = now_ms;
          }
        } else if (!ntp_synced) {
          // SLOW BLINK (No NTP): Toggle every 800ms
          if (now_ms - id(last_blink) >= 800) {
            id(onboard_led).toggle();
            id(last_blink) = now_ms;
          }
        } else {
          // SYSTEM HEALTHY: LED OFF
          id(onboard_led).turn_off();
        }

time:
  - platform: sntp
    id: sntp_time
    timezone: "GMT0BST,M3.5.0/1,M10.5.0"
    servers:
      - 0.uk.pool.ntp.org

rtttl:
  output: buzzer_out
  id: my_buzzer

globals:
  - id: fake_time_offset
    type: long
    initial_value: '0'
  - id: holiday_played
    type: bool
    initial_value: 'false'

button:
  - platform: template
    name: "Play Jingle Bells"
    icon: "mdi:music-note"
    on_press:
      - rtttl.play: "JingleBells:d=8,o=5,b=125:4e,4e,2e,4e,4e,2e,4e,4g,4c,4d,1e"
  - platform: restart
    name: "Reboot Device"
    icon: "mdi:restart"

switch:
  - platform: template
    name: "Display Power"
    id: display_toggle
    optimistic: true
    restore_mode: ALWAYS_ON
  - platform: template
    name: "Test Mode (100x Speed)"
    id: test_mode
    optimistic: true
    on_turn_off:
      lambda: 'id(fake_time_offset) = 0;'

text_sensor:
  - platform: template
    name: "Seconds to Christmas"
    id: seconds_left

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13

display:
  - platform: max7219_7segment
    id: my_display
    cs_pin: GPIO15
    num_chips: 1
    update_interval: 1s
    lambda: |-
      auto now = id(sntp_time).now();
      
      if (now.is_valid()) {
        if (id(test_mode).state) {
          id(fake_time_offset) += 3600; 
        }
        
        time_t current_epoch = now.timestamp + id(fake_time_offset);
        struct tm target;
        gmtime_r(&current_epoch, &target);
        target.tm_mon = 11;
        target.tm_mday = 25;
        target.tm_hour = 0;
        target.tm_min = 0;
        target.tm_sec = 0;
        target.tm_isdst = -1;
        
        time_t target_epoch = mktime(&target);
        
        if (current_epoch > target_epoch) {
          target.tm_year += 1;
          target_epoch = mktime(&target);
        }

        long seconds_remaining = target_epoch - current_epoch;
        id(seconds_left).publish_state(to_string(seconds_remaining));

        if (id(display_toggle).state) {
          if (now.hour >= 22 || now.hour < 7) {
            it.set_intensity(1); 
          } else {
            it.set_intensity(15);
          }
          it.printf("%08ld", seconds_remaining);
          
          if (seconds_remaining == 0 && !id(holiday_played)) {
            id(my_buzzer).play("JingleBells:d=8,o=5,b=125:4e,4e,2e,4e,4e,2e,4e,4g,4c,4d,1e");
            id(holiday_played) = true;
          } 
          if (seconds_remaining > 10) {
            id(holiday_played) = false;
          }
        } else {
          it.all_leds_off();
        }
      } else {
        it.print("SET TIME");
      }
