esphome:
  name: christmas-countdown

esp8266:
  board: nodemcuv2

# Web Server: Access via http://<device_ip> or http://christmas-countdown.local
web_server:
  port: 80

wifi:
  ssid: "YOUR_SSID"
  password: "YOUR_PASSWORD"
  fast_connect: true  # Speeds up reconnection by skipping full channel scans

# Status LED: Blinks during WiFi/NTP sync; remains OFF when system is healthy
status_led:
  pin: GPIO2 

# Time: Automatically handles UK GMT/BST transitions (British Summer Time)
time:
  - platform: sntp
    id: sntp_time
    timezone: "GMT0BST,M3.5.0/1,M10.5.0"
    servers:
      - 0.uk.pool.ntp.org
      - 1.uk.pool.ntp.org

# Audio: PWM output for the piezo buzzer on GPIO12 (D6)
output:
  - platform: esp8266_pwm
    pin: GPIO12
    id: buzzer_out

# RTTTL: Plays the "Jingle Bells" melody string
rtttl:
  output: buzzer_out
  id: my_buzzer

# State Management
globals:
  - id: fake_time_offset
    type: long
    initial_value: '0'   # Used by Test Mode to jump forward in time
  - id: holiday_played
    type: bool
    initial_value: 'false' # Prevents the buzzer from looping infinitely at 0

# Interactive Web Controls
button:
  - platform: template
    name: "Play Jingle Bells"
    icon: "mdi:music-note"
    on_press:
      - rtttl.play: "JingleBells:d=8,o=5,b=125:4e,4e,2e,4e,4e,2e,4e,4g,4c,4d,1e"

  - platform: restart
    name: "Reboot Device"
    icon: "mdi:restart"

switch:
  - platform: template
    name: "Display Power"
    id: display_toggle
    optimistic: true
    restore_mode: ALWAYS_ON

  - platform: template
    name: "Test Mode (100x Speed)"
    id: test_mode
    optimistic: true
    on_turn_off:
      lambda: 'id(fake_time_offset) = 0;'

text_sensor:
  - platform: template
    name: "Seconds to Christmas"
    id: seconds_left

# SPI: Hardware bus for the MAX7219
spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13

display:
  - platform: max7219_7segment
    id: my_display
    cs_pin: GPIO15
    num_chips: 1
    update_interval: 1s
    lambda: |-
      auto now = id(sntp_time).now();
      
      if (now.is_valid()) {
        // --- 1. TIME CALCULATION ---
        // Apply offset if 'Test Mode' is active (adds 1 hour per tick)
        if (id(test_mode).state) {
          id(fake_time_offset) += 3600; 
        }
        
        time_t current_epoch = now.timestamp + id(fake_time_offset);
        
        // Break current time down to find the current year
        struct tm target;
        gmtime_r(&current_epoch, &target);
        
        // Define target: Dec 25th, 00:00:00 of the current year
        target.tm_mon = 11;     // December (0-11)
        target.tm_mday = 25;
        target.tm_hour = 0;
        target.tm_min = 0;
        target.tm_sec = 0;
        target.tm_isdst = -1;   // Auto-determine DST for target date
        
        time_t target_epoch = mktime(&target);
        
        // --- 2. AUTOMATIC ROLLOVER ---
        // If current time > Dec 25, recalculate for the following year
        if (current_epoch > target_epoch) {
          target.tm_year += 1;
          target_epoch = mktime(&target);
        }

        long seconds_remaining = target_epoch - current_epoch;
        
        // Sync the live countdown to the web interface
        id(seconds_left).publish_state(to_string(seconds_remaining));

        // --- 3. DISPLAY & BUZZER LOGIC ---
        if (id(display_toggle).state) {
          // Night Dimming: Set intensity to 1 (22:00-07:00), else 15 (Max)
          if (now.hour >= 22 || now.hour < 7) {
            it.set_intensity(1); 
          } else {
            it.set_intensity(15);
          }
          
          // Show 8 digits with leading zeros (e.g. 00123456)
          it.printf("%08ld", seconds_remaining);
          
          // Trigger melody exactly at midnight on Christmas Day
          if (seconds_remaining == 0 && !id(holiday_played)) {
            id(my_buzzer).play("JingleBells:d=8,o=5,b=125:4e,4e,2e,4e,4e,2e,4e,4g,4c,4d,1e");
            id(holiday_played) = true;
          } 
          
          // Reset holiday flag once timer moves back to >10 seconds (new year)
          if (seconds_remaining > 10) {
            id(holiday_played) = false;
          }
        } else {
          it.all_leds_off(); // Switch is OFF in Web UI
        }
      } else {
        it.print("SET TIME"); // Waiting for WiFi/NTP Sync
      }
